<?php

/**
 * @file
 * Demonstrates common ways of interacting with the entity system.
 */

/**
 * Implements hook_menu().
 */
function entitydemo_menu()
{
  $items = array();
  $items['demo'] = array(
    'title' => 'Entity Demos',
    'description' => 'List of entity demo\'s provided by this module.',
    'access callback' => TRUE,
    'page callback' => 'entitydemo_demos',
    'menu_name' => 'navigation',
    'file' => 'includes/entitydemo.demos.inc',
  );
  $items['demo/1'] = array(
    'title' => 'Working with Existing Entities',
    'description' => 'Demonstrates API functions that make it easier to work with exsiting entities.',
    'access callback' => TRUE,
    'page callback' => 'entitydemo_demo_1',
    'file' => 'includes/entitydemo.demo1.inc',
  );
  $items['demo/2'] = array(
    'title' => 'EntityFieldQuery',
    'description' => 'Demonstrates using EntityFieldQuery',
    'access callback' => TRUE,
    'page callback' => 'entitydemo_demo_2',
    'file' => 'includes/entitydemo.demo2.inc',
  );
  return $items;
}

function entitydemo_node_view($node){
  dsm($node, 'node');

  dsm($node->content['#bundle']);

  $node_wrapper = entity_metadata_wrapper('node', $node);
  // dsm($node_wrapper->bundle());
  // dsm($node_wrapper);
  dsm($node_wrapper->author->name->value(), 'Name of Author');
  dsm($node_wrapper->author->mail->value(), 'Email of Author');
  // dsm($node_wrapper->getPropertyInfo());
  // dsm($node_wrapper->author->getPropertyInfo());
  // dsm($node_wrapper->body->getPropertyInfo());
  dsm($node_wrapper->body->value->value(), 'Body');
  
  foreach($node_wrapper->field_tags->getIterator() as $tag){
    dsm($tag->name->value(), 'Tag Name');
  }

  $node_wrapper->field_number->set(43);
  $node_wrapper->save();

}
